### ISSUE TITLE
Long usernames (slightly) mess up chat

### ISSUE THREAD

**Issue by detjensrobert** [Fiddlekins/akun-x#4]
Long usernames bump chat down a half-message, so the latest message gets cut off.
![username](https://user-images.githubusercontent.com/12376078/27014700-b10241a8-4eb2-11e7-8eb5-e7c357b8d1e1.png)

Anon (and shorter usernames) does not do this.
![anon](https://user-images.githubusercontent.com/12376078/27014715-d9802d48-4eb2-11e7-964f-ec04df3e7697.png)

Perhaps abbreviate usernames longer than 10 characters or so?

**Comment by Fiddlekins** [comment]
Oops. Best solution is probably to trim the username til it fits? So you'd have "wholewhea..." instead or something.

**Comment by Fiddlekins** [comment]
Okay, finally got around to this. It involved restructuring a good chunk of the site to makes things play nicely.
